name: Andy Phillips Photography
favicon: null
layout_spectrum: 0.984050050843507
typography_spectrum: 0.2742847956251353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4802332022227347
  lightness: 0.5251625494565815
  saturation: 0.7983521041460335
  rhythmicContrast: 0.21186099271290004
purpose: []
